name: Image

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: docker build . --file Dockerfile --tag pharndt/dnsmasq:latest
